encoders:
  dummy0:
    driver: Dummy
  dummy1:
    driver: Dummy
machines:
  milling_machine:
    axes:
      x:
        offset: 998.75
        value: 1000
      y:
        offset: 0
        value: dummy0[0] / 1000
      z:
        offset: -20
        value: -20
    name: Milling Demo
    type: milling_machine
ui:
  keyboard:
    Delete:
      action:
      - dro
      - zero
    Enter:
      action:
      - accept
    Escape:
      action:
      - cancel
    F11:
      action:
      - fullscreen
    F2:
      action:
      - navigation
      - dro
    F3:
      action:
      - navigation
      - vision
    F4:
      action:
      - navigation
      - config
    a:
      action:
      - dro
      - select
      - a
      editing: false
    alt+a:
      action:
      - dro
      - zero
      - a
    alt+b:
      action:
      - dro
      - zero
      - b
    alt+c:
      action:
      - dro
      - zero
      - c
    alt+x:
      action:
      - dro
      - zero
      - x
    alt+y:
      action:
      - dro
      - zero
      - y
    alt+z:
      action:
      - dro
      - zero
      - z
    b:
      action:
      - dro
      - select
      - b
      editing: false
    c:
      action:
      - dro
      - select
      - c
      editing: false
    ctrl+c:
      action:
      - cancel
    "shift+\xBD":
      action:
      - dro
      - half
    x:
      action:
      - dro
      - select
      - x
      editing: false
    y:
      action:
      - dro
      - select
      - y
      editing: false
    z:
      action:
      - dro
      - select
      - z
      editing: false
    "\xA7":
      action:
      - dro
      - half
  navigation:
  - id: dro
    label: DRO
  - id: vision
    label: Vision
  - id: config
    label: Config
