
encoders:
  # - id: serialport1
  #   driver: SerialPort
  #   device: /dev/ttyUSB0
  #   baud_rate: 115200
  # - id: serialport2
  #   driver: SerialPort
  #   device: /dev/ttyUSB1
  #   baud_rate: 115200
  dummy0:
    driver: Dummy
  dummy1:
    driver: Dummy
    99: sdf

machines:
  milling_machine:
    name: Milling Demo
    type: milling_machine
    axes:
      x:
        value: dummy0[0] / 1000
      y:
        value: dummy1[0] / 1000
      z:
        value: random.randint(10, 100) / 10

  # - name: Milling machine
  #   channels:
  #     x:
  #       value: serialport1[0] / 1000
  #     y:
  #       value: serialport1[1] / 1000
  #     z:
  #       value: (serialport1[2] + serialport1[3]) / 1000
  # - name: Lathe
  #   channels:
  #     x:
  #       value: serialport2[0] / 1000
  #     y:
  #       value: serialport2[1] / 1000

ui:
  navigation:
    - id: dro
      label: DRO
    - id: vision
      label: Vision
    - id: config
      label: Config
  keyboard:
    f: global, fullscreen-toggle
    F2: navigation, dro
    F3: navigation, vision
    F4: navigation, config


