encoders:
  dummy0:
    driver: Dummy
  dummy1:
    driver: Dummy
machines:
  milling_machine:
    axes:
      x:
        offset: 994
        value: 1000
      y:
        offset: 0.2
        value: dummy0[0] / 1000
      z:
        offset: -20
        value: -20
    name: Milling Demo
    type: milling_machine
ui:
  keyboard:
    ArrowDown:
      focusable:
        dir: 1
        whenEditing: false
    ArrowLeft:
      focusable.group:
        dir: -1
        whenEditing: false
    ArrowRight:
      focusable.group:
        dir: 1
        whenEditing: false
    ArrowUp:
      focusable:
        dir: -1
        whenEditing: false
    Delete:
      dro.zero: null
    Enter:
      accept: null
    Escape:
      cancel: null
    F11:
      fullscreen: null
    F2:
      navigation:
        page: dro
    F3:
      navigation:
        page: vision
    F4:
      navigation:
        page: config
    a:
      dro.select.a:
        whenEditing: false
    b:
      dro.select.b:
        whenEditing: false
    c:
      dro.select.c:
        whenEditing: false
    ctrl+c:
      cancel: null
    "shift+\xBD":
      dro.half: null
    x:
      dro.select.x:
        whenEditing: false
    y:
      dro.select.y:
        whenEditing: false
    z:
      dro.select.z:
        whenEditing: false
    "\xA7":
      dro.half: null
  navigation:
  - id: dro
    label: DRO
  - id: vision
    label: Vision
  - id: config
    label: Config
